//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilal_internet_prg_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorular()
        {
            this.Cevaplar = new HashSet<Cevaplar>();
        }
    
        public int soru_id { get; set; }
        public string soru_baslik { get; set; }
        public string soru_icerik { get; set; }
        public string foto { get; set; }
        public System.DateTime soru_tarih { get; set; }
        public int kategori_id { get; set; }
        public int uye_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cevaplar> Cevaplar { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
